import AuthReducer, {
  updateAddress,
  updateIsFirstLoad,
  updatePhoneNumber,
  updateSignUpPage2,
  updateToken,
  updateUserData,
  isLoadInit,
  isLoadSuccess,
  isLoadFailure,
  isLoginFailure,
  isLoginInit,
  isLoginSuccess,
  updateUserType,
  updateFarmerProfileDescription,
  updateFarmerProfileTags,
} from './AuthSlice';

export {
  updateAddress,
  updateIsFirstLoad,
  updatePhoneNumber,
  updateSignUpPage2,
  updateToken,
  updateUserData,
  AuthReducer,
  isLoadFailure,
  isLoadInit,
  isLoadSuccess,
  isLoginFailure,
  isLoginInit,
  isLoginSuccess,
  updateUserType,
  updateFarmerProfileDescription,
  updateFarmerProfileTags,
};
